version: '3.8'

services:
  # PostgreSQL database service
  db:
    image: postgres
    container_name: stock_scanner_db
    environment:
      POSTGRES_USER: your_psql_username
      POSTGRES_PASSWORD: your_psql_pwd
      POSTGRES_DB: stock_scanner
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  # Stock Analyzer application service
  # app:
  #   image: stock_scanner
  #   container_name: stock_scanner
  #   env_file:
  #     - .env
  #   ports:
  #     - "127.0.0.1:8888:${FLASK_PORT:-8888}"
  #   restart: always
  #   depends_on:
  #     - db
