name: Docker Build and Push

on:
  # main 分支推送时触发 & 手动执行
  push:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Get current time
      id: time
      run: echo "TIME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/llm-stock-analyzer:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/llm-stock-analyzer:${{ env.TIME }}
